services:
  swagger.route_loader:
    class: KleijnWeb\PhpApi\RoutingBundle\Routing\OpenApiRouteLoader
    arguments: ['@swagger.description.repository']
    tags:
       - { name: routing.loader }
    public: false
